### ISSUE TITLE
Share BT5 long range transmitter (nrf52840)

### ISSUE THREAD

**Issue by DamyHao** [opendroneid/opendroneid-core-c#43]
Hi,
This is my first open source contribution. I have a transmitter that emits in BT5 long range according to the RemoteID specification, using a nrf52840 dongle, and I want to share it with the community.

How do I proceed now? I create my repository and then it will be added to the opendroneid repositories?

Thanks for the help.

**Comment by gabrielcox** [comment]
How about "transmitter-nrf" (since it will likely be a good base for many NRF models).

Apache-2.0 would be great for a license choice.

**Comment by friissoren** [comment]
I created https://github.com/opendroneid/transmitter-nrf

Let me know if you have any problems uploading content there.

I took a leap of faith and added the Apache-2.0 license. If you are uncomfortable publishing your code under that license, please just let me know and we can change it.

**Comment by friissoren** [comment]
I re-read your original post and it suddenly occurred to me that you might have meant that you would like to have the repository under your own user name (https://github.com/DamyHao) and we would instead link to it from this repository?

If that was your intention, that is certainly possible also. Just let us know.

**Comment by DamyHao** [comment]
Hi,
Sorry for not responding before. I need to clean the code and look how open
source repository work. This week I have a lot of work to do (somehow
related to remoteID) so I think I will upload it on Friday. The open drone
repository is ok for me. Sorry for the inconveniences.

El dl., 30 d’ag. 2021, 8:31, friissoren ***@***.***> va
escriure:

**Comment by friissoren** [comment]
No problem. Just take all the time you need.
