### ISSUE TITLE
BUG: encodeBasicIDMessage does not initialize reserved bytes

### ISSUE THREAD

**Issue by lestofante** [opendroneid/opendroneid-core-c#54]
ODID_BasicID_encoded end with 3 reserved bytes, but are not initialized.
Other struct with reserved bytes, like ODID_OperatorID_encoded used by encodeOperatorIDMessage, get memset to 0.

I guess somewhere a unit test is also not properly checking all bytes generated, or is missing

**Comment by friissoren** [comment]
Nice catch. That is clearly inconsistently handled in different messages. Should be fixed now.
