### ISSUE TITLE
why 2550 meter area radius limit?

### ISSUE THREAD

**Issue by tridge** [opendroneid/opendroneid-core-c#58]
encodeSystemMessage() has a limit of MAX_AREA_RADIUS, which is only 2250 meters. Why such a small limit? Is there something in the FAA rules or ASTM MOC that mandates this?
I noticed this as my test setup set a 8000m radius and odid_message_build_pack() silently discarded my System message in UAS_Data. Took a while to work out what was wrong. Flights to over 2250 meters are quite common under EVLOS or BVLOS rules.

**Comment by friissoren** [comment]
Area Count, Radius, Ceiling and Floor belong together. Those are only relevant when you have more than one UA flying in a group. Together they specify the cylindrical size of the area in which the group is flying and the amount of UAs within that area.

Check the description of these fields in the ASTM F3411-22a doc.

If you are only flying a single UA, these fields can be left at their default values.
