### ISSUE TITLE
Rebroadcasting of Messages in a given Cycle

### ISSUE THREAD

**Issue by kc2rxo** [opendroneid/opendroneid-core-c#71]
All

The question I am asking came up in some personal conversations with a co-worker of mine while writing the following appendix section [1] for the DRIP Authentication draft.

We wondered if sending the same message twice, in a given duty cycle, would stay within the spirit of the RID rule and be something implementations actually perform as a computation save?

For example say we are sending at a message set rate of 2 Hz (double the required rate). A message set is defined as the set of messages consisting of Basic ID, Location, System and optionally Operator ID (depending on jurisdiction) to met the CAA requirements. Would it be in the spirit of the rule to send generate and broadcast the set in the first 1/2 second and just re-broadcast immediately, without any modifications, in the last 1/2 second?

Of course the same logic could be applied to any transport that uses Message Pack as well.

[1] https://www.ietf.org/archive/id/draft-ietf-drip-auth-30.html#name-methodology

**Comment by friissoren** [comment]
The standards only mandate the maximum transmit interval (max 1 second between sending up-to-date data). There is nothing in the standards that prevent you from transmitting the same data more often than that (just don't start spamming the air-waves with duplicate data :-)
