### ISSUE TITLE
Interest in supporting French Remote ID?

### ISSUE THREAD

**Issue by twpayne** [opendroneid/opendroneid-core-c#74]
France has its own WiFi Beacon-based Remote ID format described in https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039685188/.

Would you be interested in a PR that adds support for this format?

I would suggest adding a function similar to the existing `odid_wifi_build_message_pack_beacon_frame` function, maybe called `odid_wifi_build_french_beacon_frame`.

**Comment by friissoren** [comment]
Certainly, if you are able to provide those.

Unfortunately, I personally cannot really allocate any significant time on this activity (or most other remote ID related improvements) anymore but my belief is that anything that can be open-sourced and shared with everyone will help lessen the burden of supporting the regulatory/mandatory aspects of remote ID.

BTW: Do you know the legal status of French remote ID? My earlier assumption has been that it would be replaced with the European version of remote ID (from ASD-STAN) to align with the general EU rules, but it is of course possible that France decides to stay with their current remote ID rules/laws?

**Comment by twpayne** [comment]
Thanks for the info. I'll open a PR when I have some working code.

I've not been able to find out the legal status of the French remote ID. I also would be curious to know, especially how it interacts with EU-wide legislation.
