### ISSUE TITLE
int odid_message_process_pack

### ISSUE THREAD

**Issue by Greg-C10** [opendroneid/opendroneid-core-c#91]
wifi.c implements odid_message_process_pack from opendroneid.h.

It does not return 0 on success.  It is returning size.

from opendroneid.h:

int odid_message_process_pack(ODID_UAS_Data *UAS_Data, uint8_t *pack, size_t buflen);

/* odid_wifi_receive_message_pack_nan_action_frame - processes a received message pack
 * with each type of message from the drone information into an NAN action frame
 * @UAS_Data: general drone status information
 * @mac: mac address of the wifi adapter where the NAN frame will be sent
 * @buf: pointer to buffer space where the NAN is stored
 * @buf_size: maximum size of the buffer
 *
 * Returns 0 on success, or < 0 on error. Will fill 6 bytes into @mac.
 */

Implementation in wifi.c:

int odid_message_process_pack(ODID_UAS_Data *UAS_Data, uint8_t *pack, size_t buflen)
{
    ODID_MessagePack_encoded *msg_pack_enc = (ODID_MessagePack_encoded *) pack;
    size_t size = sizeof(*msg_pack_enc) - ODID_MESSAGE_SIZE * (ODID_PACK_MAX_MESSAGES - msg_pack_enc->MsgPackSize);
    if (size > buflen)
        return -ENOMEM;

    odid_initUasData(UAS_Data);

    if (decodeMessagePack(UAS_Data, msg_pack_enc) != ODID_SUCCESS)
        return -1;

    return (int) size;
}

**Comment by gabrielcox** [comment]
Fixed on [this commit](https://github.com/opendroneid/opendroneid-core-c/commit/910a6a33ac5116c7962e771b83262d84c0a17a11) .
